<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Entreprise extends \App\Entity\Entreprise implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'raisonSocial', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'matriculeFiscale', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'codePostal', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'fileRne', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'fileMatricule', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'logo', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'cin', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'typeEntreprise', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'users', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'fileCin', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'enable', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'tel', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'nameBrand', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'depots'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'raisonSocial', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'matriculeFiscale', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'codePostal', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'fileRne', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'fileMatricule', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'logo', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'cin', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'typeEntreprise', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'users', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'fileCin', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'enable', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'tel', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'nameBrand', '' . "\0" . 'App\\Entity\\Entreprise' . "\0" . 'depots'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Entreprise $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getRaisonSocial(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaisonSocial', []);

        return parent::getRaisonSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaisonSocial(?string $raisonSocial): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaisonSocial', [$raisonSocial]);

        return parent::setRaisonSocial($raisonSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatriculeFiscale(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatriculeFiscale', []);

        return parent::getMatriculeFiscale();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatriculeFiscale(?string $matriculeFiscale): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatriculeFiscale', [$matriculeFiscale]);

        return parent::setMatriculeFiscale($matriculeFiscale);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $adresse): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', []);

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal(string $codePostal): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', [$codePostal]);

        return parent::setCodePostal($codePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getFileRne(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFileRne', []);

        return parent::getFileRne();
    }

    /**
     * {@inheritDoc}
     */
    public function setFileRne(?string $fileRne): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFileRne', [$fileRne]);

        return parent::setFileRne($fileRne);
    }

    /**
     * {@inheritDoc}
     */
    public function getFileMatricule(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFileMatricule', []);

        return parent::getFileMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function setFileMatricule(?string $fileMatricule): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFileMatricule', [$fileMatricule]);

        return parent::setFileMatricule($fileMatricule);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', []);

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo(?string $logo): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', [$logo]);

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCin(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCin', []);

        return parent::getCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCin(?string $cin): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCin', [$cin]);

        return parent::setCin($cin);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeEntreprise(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeEntreprise', []);

        return parent::getTypeEntreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeEntreprise(string $typeEntreprise): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeEntreprise', [$typeEntreprise]);

        return parent::setTypeEntreprise($typeEntreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', []);

        return parent::getUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function addUser(\App\Entity\User $user): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUser', [$user]);

        return parent::addUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUser(\App\Entity\User $user): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUser', [$user]);

        return parent::removeUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getFileCin(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFileCin', []);

        return parent::getFileCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setFileCin(?string $fileCin): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFileCin', [$fileCin]);

        return parent::setFileCin($fileCin);
    }

    /**
     * {@inheritDoc}
     */
    public function isEnable(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnable', []);

        return parent::isEnable();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnable(bool $enable): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnable', [$enable]);

        return parent::setEnable($enable);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel(?string $tel): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$tel]);

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameBrand(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameBrand', []);

        return parent::getNameBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameBrand(?string $nameBrand): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameBrand', [$nameBrand]);

        return parent::setNameBrand($nameBrand);
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepots(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepots', []);

        return parent::getDepots();
    }

    /**
     * {@inheritDoc}
     */
    public function addDepot(\App\Entity\Depot $depot): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDepot', [$depot]);

        return parent::addDepot($depot);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDepot(\App\Entity\Depot $depot): \App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDepot', [$depot]);

        return parent::removeDepot($depot);
    }

}
