<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWNj2lLI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWNj2lLI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWNj2lLI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWNj2lLI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWNj2lLI\App_KernelDevDebugContainer([
    'container.build_hash' => 'WNj2lLI',
    'container.build_id' => '0a75055c',
    'container.build_time' => 1694691412,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWNj2lLI');
